### ISSUE TITLE
sql 연결 방화벽이슈

### ISSUE THREAD

**Issue by hyeinhyun** [ilgwonPark2/SystemAnalysisDesign#19]

**Comment by hyeinhyun** [comment]
1. 환경 세팅 다시-->조사 필요
2. 서버에서 돌리기-->필요한 모듈 , 크롬드라이버 설치

**Comment by ilgwonPark2** [comment]
어떤 방화벽 이슈를 말하는거죠???

**Comment by hyeinhyun** [comment]
지금 로컬과 4900포트는 연결이됐는데, 연결후 3306포트로 들어가려하니 패킷이 전달이느려 접속이 안된다는 에러가뜨네요. 패킷전달이 느린이유가 방화벽때문이라는 글이많아 확인해보려합니다

**Comment by ilgwonPark2** [comment]
연결후 3306 포트로 들어가는 이유가 있을까요??
아 비밀번호 변경되었습니다. 슬랙 참고해주세요

**Comment by hyeinhyun** [comment]
ssh 터널을 이용해 들어가려고 했는데, 다른 방법 모색중입니다

**Comment by ilgwonPark2** [comment]
원인: 서버 밖의 환경에서 db 접속. ~> 터널링 ~> 속도저하.

**Comment by ilgwonPark2** [comment]
fixed with @hyeinhyun 
https://zetawiki.com/wiki/MySQL_원격_접속_허용
